routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\BalitaController;
use App\Http\Controllers\BumilController;
use App\Http\Controllers\CheckupController;
use App\Http\Controllers\DokumentasiController;
use App\Http\Controllers\DokumentController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\HomeController;
// use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ImunisasiController;
use App\Http\Controllers\KaderController;
use App\Http\Controllers\ManajemenUserController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\ShowArticleController;
use App\Http\Controllers\SuperAdminAuthenticateController;
use App\Http\Controllers\SuperAdminHomepageController;
use App\Http\Controllers\VaksinasiController;
use App\Http\Controllers\VitaminController;
use App\Models\Article;
use App\Models\Balita;
use App\Models\Bumil;
use App\Models\Checkup;
use App\Models\Dokument;
use App\Models\Imunisasi;
use App\Models\Kader;
use App\Models\Vaksinasi;
use App\Models\Vitamin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('mainpage');
Route::get('/article/{article}', ShowArticleController::class)->name('show.article');

Route::get('/dashboard', function () {
    return view('dashboard', [
        'kader' => Kader::count(),
        'balita' => Balita::count(),
        'vitamin' => Vitamin::count(),
        'imunisasi' => Imunisasi::count(),
        'vaksinasi' => Vaksinasi::count(),
        'checkup' => Checkup::count(),
        'bumil' => Bumil::count(),
        'article' => Article::count(),
        'dokumen' => Dokument::count()
    ]);
})->middleware('auth')->name('dashboard');

Route::resource('/dashboard/kader', KaderController::class)->middleware('auth');
Route::resource('/dashboard/balita', BalitaController::class)->middleware('auth');
Route::resource('/dashboard/bumil', BumilController::class)->middleware('auth');
Route::resource('/dashboard/vitamin', VitaminController::class)->middleware('auth');
Route::resource('/dashboard/imunisasi', ImunisasiController::class)->middleware('auth');
Route::resource('/dashboard/vaksinasi', VaksinasiController::class)->middleware('auth');
Route::resource('/dashboard/article', ArticleController::class)->middleware('auth');
Route::resource('/dashboard/checkup', CheckupController::class)->middleware('auth');
Route::resource('/dashboard/dokumen', FileController::class)->middleware('auth');
Route::get('/dashboard/dokumen/download/{id}', [FileController::class, 'download'])->middleware('auth');
Route::get('/dashboard/dokumen/view/{id}',[FileController::class,'view'])->middleware('auth');

Route::middleware('guest')->group(function(){
    Route::controller(ResetPasswordController::class)->group(function (){
        Route::get('lupa-password', 'view')->name('lupa-password.view');
        Route::post('verify-email', 'verifyEmail')->name('verify.email');
        Route::get('reset-password', 'resetPasswordView')->name('reset-password.view');
        Route::post('lupa-password', 'reset')->name('lupa-password.store');
    }); 
});

Route::controller(SuperAdminAuthenticateController::class)->group(function(){
    Route::get('admin/login', 'loginView')->name('admin.login.view');
    Route::post('admin/login', 'login')->name('admin.login');
    Route::post('admin/logout', 'logout')->name('admin.logout');
});

Route::middleware('auth:superadmin')->group(function() {
    Route::get('admin/dashboard', [SuperAdminHomepageController::class, 'index'])->name('admin.index');

    Route::controller(ManajemenUserController::class)->group(function() {
        Route::get('admin/data-users', 'index')->name('user.index');
        Route::get('admin/tambah-user', 'addUser')->name('user.add');
        Route::post('admin/tambah-user', 'storeUser')->name('user.store');
        Route::delete('admin/hapus-user/{id}', 'deleteUser')->name('user.delete');
        Route::get('admin/data-user/{id}/ubah-password', 'ubahPasswordView')->name('user.changePwd');
        Route::post('admin/data-user/{id}/ubah-password', 'ubahPassword')->name('user.changePwdStore');
    });
});

require __DIR__.'/auth.php';

app/Models/Bumil.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bumil extends Model
{
    use HasFactory;

    protected $table = 'bumil';

    // protected $fillable = [
    //     'nama_ibu', 'NIK', 'umur', 'alamat', 'masa_kehamilan', 'checkup_ke'
    // ];
    protected $guarded = [];
}

app/Http/Controllers/BumilController.php
<?php

namespace App\Http\Controllers;


use App\Models\Bumil;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class BumilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Bumil::all();
        $sweetalert_delete_title = 'Delete Data Ibu Hamil!';
        $sweetalert_delete_msg = "Apakah yakin ingin hapus data ibu hamil?";
        confirmDelete($sweetalert_delete_title, $sweetalert_delete_msg);
        return view('bumil.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bumil.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'nama_ibu' => 'required',
            'NIK' => 'required',
            'umur_tahun' => 'required|numeric',
            'umur_bulan' => [
                'required',
                Rule::in(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'])
            ],
            'alamat' => 'required',
            'masa_kehamilan' => 'required',
            'checkup_ke' => 'required'
        ]);

        Bumil::create($data);
        return redirect('/dashboard/bumil')->with('success', 'Data Ibu Hamil Berhasil di Tambahkan');;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Bumil::findOrFail($id);

        return view('bumil.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bumil $bumil)
    {
        // $request->validate([
        //     'nama_ibu' => 'required',
        //     'NIK' => 'required',
        //     'umur_tahun' => 'required|numeric',
        //     'umur_bulan' => [
        //         'required',
        //         Rule::in(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'])
        //     ],
        //     'alamat' => 'required',
        //     'masa_kehamilan' => 'required',
        //     'checkup_ke' => 'required'
        // ]);

        $data = [
            'nama_ibu' => $request->nama_ibu,
            'NIK' => $request->NIK,
            'umur_tahun' => $request->umur_tahun,
            'umur_bulan' => $request->umur_bulan,
            'alamat' => $request->alamat,
            'masa_kehamilan' => $request->masa_kehamilan
        ];

        $bumil->update($data);

        return redirect('/dashboard/bumil')->with('info', 'Data Ibu Hamil Berhasil di Update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { 
        $item = Bumil::findOrFail($id);

        $item->delete();
        return redirect('/dashboard/bumil')->with('danger', 'Data Ibu Hamil Berhasil di Hapus');
    }
}

resources/views/bumil/create.blade.php
{{-- @extends('app-layouts.admin.index')

@section('content')
    <div class="content-wrapper">
        <section>
            <div class="row">
                <div class="col-lg-8">
                    <div class="card my-4">
                        <div class="card-header">
                            <div class="card-title">
                                <h5>Tambah Kader</h5>
                            </div>
                        </div>
                        <div class="card-shadow">
                            <div class="card-body">
                                <form action="/dashboard/kader" method="POST">
                                    @csrf
                                    <div class="form-group">
                                        <label for="nama">Nama</label>
                                        <input type="text" class="form-control @error('nama') is-invalid @enderror"" name="nama" placeholder="Nama" value="{{ old('nama') }}">
                                        @error('nama')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="alamat">Alamat</label>
                                        <textarea name="alamat" id="alamat" cols="20" rows="5" class="form-control @error('alamat') is-invalid @enderror"">{{ old('alamat') }}</textarea>
                                        @error('alamat')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="umur">Umur</label>
                                        <input type="text" class="form-control @error('umur') is-invalid @enderror"" name="umur" placeholder="Umur" value="{{ old('umur') }}">
                                        @error('umur')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="jabatan">Jabatan</label>
                                        <input type="text" class="form-control @error('jabatan') is-invalid @enderror" name="jabatan" placeholder="Jabatan" value="{{ old('jabatan') }}">
                                        @error('jabatan')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="status">Status</label>
                                        <input type="text" class="form-control @error('status') is-invalid @enderror"" name="status" placeholder="status" value="{{ old('status') }}">
                                        @error('status')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <button class="btn btn-primary btn-block" type="submit">Simpan</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection --}}

@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Tambah Data</h1>
      </div>
      <div class="section-body">
        <h2 class="section-title">Form Input Data Ibu Hamil</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
              <form action="/dashboard/bumil" method="POST">
                @csrf
                <div class="card-header">
                  <h4>Masukkan Data Ibu Hamil Dengan Sesuai</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="nama_ibu">Nama Ibu</label>
                        <input type="text" class="form-control @error('nama_ibu') is-invalid @enderror"" name="nama_ibu" placeholder="Nama Ibu" value="{{ old('nama_ibu') }}">
                        @error('nama_ibu')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="NIK">NIK</label>
                        <input type="text" class="form-control @error('NIK') is-invalid @enderror"" name="NIK" placeholder="NIK" value="{{ old('NIK') }}">
                        @error('NIK')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="umur_tahun">Umur (Tahun)</label>
                        <input type="text" class="form-control @error('umur_tahun') is-invalid @enderror"" name="umur_tahun" placeholder="Umur" value="{{ old('umur_tahun') }}" id="umur_tahun">
                        @error('umur_tahun')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="umur_bulan">Umur (Bulan)</label>
                        <input type="text" class="form-control @error('umur_bulan') is-invalid @enderror"" name="umur_bulan" placeholder="Umur" value="{{ old('umur_bulan') }}" id="umur_bulan">
                        @error('umur_bulan')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <textarea name="alamat" id="alamat" cols="20" rows="5" class="form-control @error('alamat') is-invalid @enderror"">{{ old('alamat') }}</textarea>
                        @error('alamat')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="masa_kehamilan">Masa Kehamilan</label>
                        <input type="text" class="form-control @error('masa_kehamilan') is-invalid @enderror"" name="masa_kehamilan" placeholder="Masa Kehamilan" value="{{ old('masa_kehamilan') }}">
                        @error('masa_kehamilan')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="checkup_ke">Checkup Ke</label>
                        <input type="text" class="form-control @error('checkup_ke') is-invalid @enderror"" name="checkup_ke" placeholder="Checkup Ke" value="{{ old('checkup_ke') }}">
                        @error('checkup_ke')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                </div>
                <div class="card-footer text-right">
                  <button class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/bumil/edit.blade.php
{{-- @extends('app-layouts.admin.index')

@section('content')
    <div class="content-wrapper">
        <section>
            <div class="row">
                <div class="col-lg-8">
                    <div class="card my-4">
                        <div class="card-header">
                            <div class="card-title">
                                <h5>Tambah Kader</h5>
                            </div>
                        </div>
                        <div class="card-shadow">
                            <div class="card-body">
                                <form action="/dashboard/kader/{{ $data->id }}" method="POST">
                                    @method('PUT')
                                    @csrf
                                    <div class="form-group">
                                        <label for="nama">Nama</label>
                                        <input type="text" class="form-control @error('nama') is-invalid @enderror"" name="nama" placeholder="Nama" value="{{ $data->nama }}">
                                        @error('nama')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="alamat">Alamat</label>
                                        <textarea name="alamat" id="alamat" cols="20" rows="5" class="form-control @error('alamat') is-invalid @enderror">{{ $data->alamat }}</textarea>
                                        @error('alamat')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="umur">Umur</label>
                                        <input type="text" class="form-control @error('umur') is-invalid @enderror"" name="umur" placeholder="Umur" value="{{ $data->umur }}">
                                        @error('umur')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="jabatan">Jabatan</label>
                                        <input type="text" class="form-control @error('jabatan') is-invalid @enderror" name="jabatan" placeholder="Jabatan" value="{{ $data->jabatan }}">
                                        @error('jabatan')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="status">Status</label>
                                        <input type="text" class="form-control @error('status') is-invalid @enderror"" name="status" placeholder="status" value="{{ $data->status }}">
                                        @error('status')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <button class="btn btn-primary btn-block" type="submit">Simpan</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection --}}

@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Update Data</h1>
      </div>
      <div class="section-body">
        <h2 class="section-title">Form Input Data Ibu Hamil</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
                {{-- <form action="/dashboard/bumil/{{ $data->id }}" method="POST"> --}}
                <form action="{{ route('bumil.update', [
                    'bumil' => $data->id
                ]) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="card-header">
                    <h4>Masukkan Data Ibu Hamil Dengan Sesuai</h4>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="nama_ibu">Nama Ibu</label>
                            <input type="text" class="form-control @error('nama_ibu') is-invalid @enderror" name="nama_ibu" placeholder="Nama Ibu" value="{{ $data->nama_ibu }}">
                            @error('nama_ibu')
                                <div class="invalid-feedback">
                                {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="NIK">NIK</label>
                            <input type="text" class="form-control @error('NIK') is-invalid @enderror" name="NIK" placeholder="NIK" value="{{ $data->NIK }}" required>
                            @error('NIK')
                                <div class="invalid-feedback">
                                {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="umur_tahun">Umur (Tahun)</label>
                            <input type="text" class="form-control @error('umur_tahun') is-invalid @enderror" name="umur_tahun" placeholder="Umur (tahun)" value="{{ $data->umur_tahun }}" required>
                            @error('umur_tahun')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="umur_bulan">Umur (Bulan)</label>
                            <input type="text" class="form-control @error('umur_bulan') is-invalid @enderror" name="umur_bulan" placeholder="Umur (Bulan)" value="{{ $data->umur_bulan }}" required>
                            @error('umur_bulan')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="alamat">Alamat</label>
                            <textarea name="alamat" id="alamat" cols="20" rows="5" class="form-control @error('alamat') is-invalid @enderror" required>{{ $data->alamat }}</textarea>
                            @error('alamat')
                                <div class="invalid-feedback">
                                {{ $message }}
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="masa_kehamilan">Masa Kehamilan</label>
                            <input type="text" class="form-control @error('masa_kehamilan') is-invalid @enderror" name="masa_kehamilan" placeholder="Masa Kehamilan" value="{{ $data->masa_kehamilan }}" required>
                            @error('masa_kehamilan')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-primary" type="submit" id="tes">Submit</button>
                    </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/bumil/index.blade.php
@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Data Ibu Hamil</h1>
      </div>
      @include('includes.admin.alert')
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header d-inline">
              <h4>Data Posyandu</h4>
              <a href="/dashboard/bumil/create" class=" btn btn-primary mt-3">Tambah Data Ibu Hamil</a>
              <a href="#" class=" btn btn-primary mt-3">Unduh Data</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-striped" id="table-1">
                  <thead>
                    <tr>
                      <th class="text-center">
                        No
                      </th>
                      <th>Nama Ibu</th>
                      <th>NIK</th>
                      <th>Umur</th>
                      <th>Alamat</th>
                      <th>Masa Kehamilan</th>
                      <th>Checkup Ke</th>
                      <th>Aksi</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($data as $item)
                  <tr>
                    <th class="text-center">{{ $loop->iteration}}</th>
                    <th>{{ $item->nama_ibu}}</th>
                    <th>{{ $item->NIK }}</th>
                    <th>
                      {{ $item->umur_tahun }} tahun {{ $item->umur_bulan }} bulan
                    </th>
                    <th>{{ $item->alamat }}</th>
                    <th>{{ $item->masa_kehamilan }}</th>
                    <th>{{ $item->checkup_ke }}</th>
                    <td>
                        <a href="/dashboard/bumil/{{ $item->id }}/edit" class="btn btn-info">
                        <i class="fa fa-pencil-alt"></i>
                        </a>
                        <a href="{{ route('bumil.destroy', $item->id) }}" class="btn btn-danger" data-confirm-delete="true">
                          <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
                  @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="section-body">
      </div>
    </section>
  </div>
@endsection