routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\BalitaController;
use App\Http\Controllers\BumilController;
use App\Http\Controllers\CheckupController;
use App\Http\Controllers\DokumentasiController;
use App\Http\Controllers\DokumentController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\HomeController;
// use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ImunisasiController;
use App\Http\Controllers\KaderController;
use App\Http\Controllers\ManajemenUserController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\ShowArticleController;
use App\Http\Controllers\SuperAdminAuthenticateController;
use App\Http\Controllers\SuperAdminHomepageController;
use App\Http\Controllers\VaksinasiController;
use App\Http\Controllers\VitaminController;
use App\Models\Article;
use App\Models\Balita;
use App\Models\Bumil;
use App\Models\Checkup;
use App\Models\Dokument;
use App\Models\Imunisasi;
use App\Models\Kader;
use App\Models\Vaksinasi;
use App\Models\Vitamin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('mainpage');
Route::get('/article/{article}', ShowArticleController::class)->name('show.article');

Route::get('/dashboard', function () {
    return view('dashboard', [
        'kader' => Kader::count(),
        'balita' => Balita::count(),
        'vitamin' => Vitamin::count(),
        'imunisasi' => Imunisasi::count(),
        'vaksinasi' => Vaksinasi::count(),
        'checkup' => Checkup::count(),
        'bumil' => Bumil::count(),
        'article' => Article::count(),
        'dokumen' => Dokument::count()
    ]);
})->middleware('auth')->name('dashboard');

Route::resource('/dashboard/kader', KaderController::class)->middleware('auth');
Route::resource('/dashboard/balita', BalitaController::class)->middleware('auth');
Route::resource('/dashboard/bumil', BumilController::class)->middleware('auth');
Route::resource('/dashboard/vitamin', VitaminController::class)->middleware('auth');
Route::resource('/dashboard/imunisasi', ImunisasiController::class)->middleware('auth');
Route::resource('/dashboard/vaksinasi', VaksinasiController::class)->middleware('auth');
Route::resource('/dashboard/article', ArticleController::class)->middleware('auth');
Route::resource('/dashboard/checkup', CheckupController::class)->middleware('auth');
Route::resource('/dashboard/dokumen', FileController::class)->middleware('auth');
Route::get('/dashboard/dokumen/download/{id}', [FileController::class, 'download'])->middleware('auth');
Route::get('/dashboard/dokumen/view/{id}',[FileController::class,'view'])->middleware('auth');

Route::middleware('guest')->group(function(){
    Route::controller(ResetPasswordController::class)->group(function (){
        Route::get('lupa-password', 'view')->name('lupa-password.view');
        Route::post('verify-email', 'verifyEmail')->name('verify.email');
        Route::get('reset-password', 'resetPasswordView')->name('reset-password.view');
        Route::post('lupa-password', 'reset')->name('lupa-password.store');
    }); 
});

Route::controller(SuperAdminAuthenticateController::class)->group(function(){
    Route::get('admin/login', 'loginView')->name('admin.login.view');
    Route::post('admin/login', 'login')->name('admin.login');
    Route::post('admin/logout', 'logout')->name('admin.logout');
});

Route::middleware('auth:superadmin')->group(function() {
    Route::get('admin/dashboard', [SuperAdminHomepageController::class, 'index'])->name('admin.index');

    Route::controller(ManajemenUserController::class)->group(function() {
        Route::get('admin/data-users', 'index')->name('user.index');
        Route::get('admin/tambah-user', 'addUser')->name('user.add');
        Route::post('admin/tambah-user', 'storeUser')->name('user.store');
        Route::delete('admin/hapus-user/{id}', 'deleteUser')->name('user.delete');
        Route::get('admin/data-user/{id}/ubah-password', 'ubahPasswordView')->name('user.changePwd');
        Route::post('admin/data-user/{id}/ubah-password', 'ubahPassword')->name('user.changePwdStore');
    });
});

require __DIR__.'/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Article extends Model
{
    use HasFactory;

    const EXCERPT_LENGTH = 100;

    protected $table = 'article';

    protected $fillable = ['title', 'body', 'image'];

    public function excerpt()
    {
        return Str::limit($this->body, Article::EXCERPT_LENGTH);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Article::all();
        $sweetalert_delete_title = 'Delete Data Artikel!';
        $sweetalert_delete_msg = "Apakah yakin ingin hapus data artikel?";
        confirmDelete($sweetalert_delete_title, $sweetalert_delete_msg);
        return view('article.index', compact('data')
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('article.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'title'=> 'required|max:255',
            'image'=>'image|file|max:1024'
        ]);
        $data['body'] = Str::limit(strip_tags($request->body), 200);
        if($request->file('image')){
            $data['image'] = $request->file('image')->store('article-images');
        }

        Article::create($data);
        return redirect('/dashboard/article')->with('success', 'Informasi Kegiatan Berhasil Di Tambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Article::findOrFail($id);
        return view('article.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'title'=> 'required|max:255',
            'body'=> 'required',
            'image'=>'image|file|max:1024'
        ]);

        $item = Article::findOrFail($id);

        if($request->file('image')){
            if($request->oldImage){
                    Storage::delete($request->oldImage);
                }
            $data['image'] = $request->file('image')->store('article-images');
        }

        $item->update($data);
        return redirect('/dashboard/article')->with('info', 'Informasi Kegiatan Berhasil Di Update');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        if($article->image){
            Storage::delete($article->image);
        }

        Article::destroy($article->id);

        return redirect('/dashboard/article');

    }
}

resources/views/article/create.blade.php
{{-- @extends('app-layouts.admin.index')

@section('content')
    <div class="content-wrapper">
        <section>
            <div class="row">
                <div class="col-lg-8">
                    <div class="card my-4">
                        <div class="card-header">
                            <div class="card-title">
                                <h5>Tambah Article</h5>
                            </div>
                        </div>
                        <div class="card-shadow">
                            <div class="card-body">
                                <form action="/dashboard/article" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input type="text" class="form-control @error('title') is-invalid @enderror"" name="title" placeholder="Judul" value="{{ old('title') }}">
                                        @error('title')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="body">Body</label>
                                        <textarea name="body" id="body" cols="20" rows="5" class="form-control @error('body') is-invalid @enderror"">{{ old('body') }}</textarea>
                                        @error('body')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="image">Image</label>
                                        <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" placeholder="image" value="{{ old('image') }}">
                                        @error('image')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <button class="btn btn-primary btn-block" type="submit">Simpan</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection --}}

@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Tambah Data</h1>
      </div>
      <div class="section-body">
        <h2 class="section-title">Form Input Data Kegiatan</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
                <form action="/dashboard/article" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card-header">
                  <h4>Masukkan Data Kegiatan Dengan Sesuai</h4>
                </div>
                <div class="card-body">
                    <div class="form-group row mb-4">
                      <label for="title" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Judul</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Judul" value="{{ old('title') }}">
                      </div>
                      @error('title')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                      @enderror
                    </div>
                    <div class="form-group row mb-4">
                      <label for="body" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                      <div class="col-sm-12 col-md-7">
                        <textarea name="body" id="body" class="summernote @error('body') is-invalid @enderror">{{ old('body') }}</textarea>
                      </div>
                      @error('title')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                      @enderror
                    </div>
                    <div class="form-group row mb-4">
                        <label for="image" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Gambar</label>
                        <div class="col-sm-12 col-md-7">
                          <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" placeholder="image" value="{{ old('image') }}">
                        </div>
                      </div>
                      @error('title')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                      @enderror
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                      <div class="col-sm-12 col-md-7">
                        <button class="btn btn-primary">Publish</button>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/article/edit.blade.php
@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Update Data</h1>
      </div>
      <div class="section-body">
        <h2 class="section-title">Form Input Data Informasi Kegiatan</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
                <form action="/dashboard/article/{{ $data->id }}" method="POST" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="card-header">
                  <h4>Masukkan Data Kegiatan Dengan Sesuai</h4>
                </div>
                <div class="card-body">
                    <div class="form-group row mb-4">
                      <label for="title" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Judul</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Judul" value="{{ $data->title}}">
                      </div>
                      @error('title')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                      @enderror
                    </div>
                    <div class="form-group row mb-4">
                      <label for="body" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                      <div class="col-sm-12 col-md-7">
                        <textarea name="body" id="body" class="summernote @error('body') is-invalid @enderror">{{ $data->body }}</textarea>
                      </div>
                      @error('body')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                      @enderror
                    </div>
                    <div class="form-group row mb-4">
                        <label for="image" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Gambar</label>
                        <input class="form-control" type="hidden" name="oldImage" value="{{ $data->image }}">
                        <div class="col-sm-12 col-md-7">
                          <input type="file" class="form-control  @error('image') is-invalid @enderror" name="image" placeholder="image" value="{{ $data->image }}">
                        </div>
                      @error('image')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                      @enderror
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                      <div class="col-sm-12 col-md-7">
                        <button class="btn btn-primary">Publish</button>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/article/index.blade.php
@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Data List Kegiatan</h1>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header d-inline">
              <h4>Data Kegiatan</h4>
              <a href="/dashboard/article/create" class=" btn btn-primary mt-3">Tambah Data Kegiatan </a>
              <a href="#" class=" btn btn-primary mt-3">Unduh Data</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-striped" id="table-1">
                  <thead>
                    <tr>
                      <th class="text-center">
                        No
                      </th>
                      <th>Judul</th>
                      <th>Content</th>
                      <th>Image</th>
                      <th>Aksi</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($data as $item)
                    <tr>
                      {{-- <input type="hidden" class="delete_id" value="{{ $item->id }}"> --}}
                      <th class="text-center">{{ $loop->iteration}}</th>
                      <th>{{ $item->title }}</th>
                      <th>{{ $item->body }}</th>
                      <th>
                        <img src="{{ asset('storage/'. $item->image) }}" alt="" class="" style="height: 100px;">
                      </th>
                      <td>
                          <a href="/dashboard/article/{{ $item->id }}/edit" class="btn btn-info">
                          <i class="fa fa-pencil-alt"></i>
                          </a>
                          <a href="{{ route('article.destroy', $item->id) }}" class="btn btn-danger" data-confirm-delete="true">
                            <i class="fa fa-trash"></i>
                          </a>
                      </td>
                  </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="section-body">
      </div>
    </section>
  </div>
@endsection

resources/views/article/show.blade.php
@extends('app-layouts.index')

@section('content')
    <div class="container mt-4">
        <div class="card">
            <img src="{{ asset('storage/'. $data->image) }}" 
                class="card-img-top img-fluid" alt="..."
            >
            <div class="card-body">
              <h5 class="card-title">{{ $data->title }}</h5>
              <p class="card-text">{{ $data->body }}</p>
              <small class="text-muted">
                Created at: {{ \Carbon\Carbon::parse($data->created_at)->translatedFormat('d F Y') }}
              </small>
            </div>
          </div>
    </div>
@endsection