routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\BalitaController;
use App\Http\Controllers\BumilController;
use App\Http\Controllers\CheckupController;
use App\Http\Controllers\DokumentasiController;
use App\Http\Controllers\DokumentController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\HomeController;
// use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ImunisasiController;
use App\Http\Controllers\KaderController;
use App\Http\Controllers\ManajemenUserController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\ShowArticleController;
use App\Http\Controllers\SuperAdminAuthenticateController;
use App\Http\Controllers\SuperAdminHomepageController;
use App\Http\Controllers\VaksinasiController;
use App\Http\Controllers\VitaminController;
use App\Models\Article;
use App\Models\Balita;
use App\Models\Bumil;
use App\Models\Checkup;
use App\Models\Dokument;
use App\Models\Imunisasi;
use App\Models\Kader;
use App\Models\Vaksinasi;
use App\Models\Vitamin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('mainpage');
Route::get('/article/{article}', ShowArticleController::class)->name('show.article');

Route::get('/dashboard', function () {
    return view('dashboard', [
        'kader' => Kader::count(),
        'balita' => Balita::count(),
        'vitamin' => Vitamin::count(),
        'imunisasi' => Imunisasi::count(),
        'vaksinasi' => Vaksinasi::count(),
        'checkup' => Checkup::count(),
        'bumil' => Bumil::count(),
        'article' => Article::count(),
        'dokumen' => Dokument::count()
    ]);
})->middleware('auth')->name('dashboard');

Route::resource('/dashboard/kader', KaderController::class)->middleware('auth');
Route::resource('/dashboard/balita', BalitaController::class)->middleware('auth');
Route::resource('/dashboard/bumil', BumilController::class)->middleware('auth');
Route::resource('/dashboard/vitamin', VitaminController::class)->middleware('auth');
Route::resource('/dashboard/imunisasi', ImunisasiController::class)->middleware('auth');
Route::resource('/dashboard/vaksinasi', VaksinasiController::class)->middleware('auth');
Route::resource('/dashboard/article', ArticleController::class)->middleware('auth');
Route::resource('/dashboard/checkup', CheckupController::class)->middleware('auth');
Route::resource('/dashboard/dokumen', FileController::class)->middleware('auth');
Route::get('/dashboard/dokumen/download/{id}', [FileController::class, 'download'])->middleware('auth');
Route::get('/dashboard/dokumen/view/{id}',[FileController::class,'view'])->middleware('auth');

Route::middleware('guest')->group(function(){
    Route::controller(ResetPasswordController::class)->group(function (){
        Route::get('lupa-password', 'view')->name('lupa-password.view');
        Route::post('verify-email', 'verifyEmail')->name('verify.email');
        Route::get('reset-password', 'resetPasswordView')->name('reset-password.view');
        Route::post('lupa-password', 'reset')->name('lupa-password.store');
    }); 
});

Route::controller(SuperAdminAuthenticateController::class)->group(function(){
    Route::get('admin/login', 'loginView')->name('admin.login.view');
    Route::post('admin/login', 'login')->name('admin.login');
    Route::post('admin/logout', 'logout')->name('admin.logout');
});

Route::middleware('auth:superadmin')->group(function() {
    Route::get('admin/dashboard', [SuperAdminHomepageController::class, 'index'])->name('admin.index');

    Route::controller(ManajemenUserController::class)->group(function() {
        Route::get('admin/data-users', 'index')->name('user.index');
        Route::get('admin/tambah-user', 'addUser')->name('user.add');
        Route::post('admin/tambah-user', 'storeUser')->name('user.store');
        Route::delete('admin/hapus-user/{id}', 'deleteUser')->name('user.delete');
        Route::get('admin/data-user/{id}/ubah-password', 'ubahPasswordView')->name('user.changePwd');
        Route::post('admin/data-user/{id}/ubah-password', 'ubahPassword')->name('user.changePwdStore');
    });
});

require __DIR__.'/auth.php';

resources/views/dokumen/create.blade.php
{{-- @extends('app-layouts.admin.index')

@section('content')
    <div class="content-wrapper">
        <section>
            <div class="row">
                <div class="col-lg-8">
                    <div class="card my-4">
                        <div class="card-header">
                            <div class="card-title">
                                <h5>Tambah File</h5>
                            </div>
                        </div>
                        <div class="card-shadow">
                            <div class="card-body">
                                <form action="/dashboard/dokumen" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group">
                                        <label for="nama">Nama</label>
                                        <input type="text" class="form-control @error('nama') is-invalid @enderror"" name="nama" placeholder="Nama File" value="{{ old('nama') }}">
                                        @error('nama')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="deskripsi">Deskripsi</label>
                                        <input type="text" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" placeholder="Deskripsi" value="{{ old('deskripsi') }}">
                                        @error('deskripsi')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="file">File</label>
                                        <input type="file" class="form-control @error('file') is-invalid @enderror" name="file" placeholder="file" value="{{ old('file') }}">
                                        @error('file')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <button class="btn btn-primary btn-block" type="submit">Simpan</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection --}}

@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Tambah File</h1>
      </div>
      <div class="section-body">
        <h2 class="section-title">Form Input File Posyandu</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
              <form action="/dashboard/dokumen" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="card-header">
                  <h4>Masukkan File Posyandu</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="nama">Nama</label>
                        <input type="text" class="form-control @error('nama') is-invalid @enderror"" name="nama" placeholder="Nama File" value="{{ old('nama') }}">
                        @error('nama')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <input type="text" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" placeholder="Deskripsi" value="{{ old('deskripsi') }}">
                        @error('deskripsi')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="file">File</label>
                        <input type="file" class="form-control @error('file') is-invalid @enderror" name="file" placeholder="file" value="{{ old('file') }}">
                        @error('file')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                </div>
                <div class="card-footer text-right">
                  <button class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/dokumen/edit.blade.php
@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Update Data</h1>
      </div>
      <div class="section-body">
        <h2 class="section-title">Form Input File Posyandu</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
                <form action="/dashboard/dokumen/{{ $data->id }}" method="POST" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="card-header">
                  <h4>Masukkan File Posyandu Dengan Sesuai</h4>
                </div>
                <div class="card-body">
                    <div class="form-group row mb-4">
                      <label for="deskripsi" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama File</label>
                      <div class="col-sm-12 col-md-7">
                        <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" placeholder="Nama File" value="{{ $data->nama}}">
                      </div>
                      @error('nama')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                      @enderror
                    </div>
                    <div class="form-group row mb-4">
                        <label for="deskripsi" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Deskripsi</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="text" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" placeholder="deskripsi File" value="{{ $data->deskripsi}}">
                          </div>
                        @error('deskripsi')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group row mb-4">
                        <label for="file" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Masukkan File</label>
                        <input class="form-control" type="hidden" name="oldfile" value="{{ $data->file }}">
                        <div class="col-sm-12 col-md-7">
                          <input type="file" class="form-control name="oldFile"  @error('file') is-invalid @enderror" name="file" placeholder="file" value="{{ $data->file }}">
                        </div>
                      @error('file')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                      @enderror
                    </div>
                    <div class="form-group row mb-4">
                      <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                      <div class="col-sm-12 col-md-7">
                        <button class="btn btn-primary">Update</button>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/dokumen/index.blade.php
{{-- @extends('app-layouts.admin.index')

@section('content')
<section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="d-sm-flex justify-content-start my-3">
            <a href="/dashboard/dokumen/create" class="btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-50"></i> Tambah File</a>
        </div>
        @if(session()->has('success'))
          <div class="alert alert-success col-lg-12" role="alert">
            {{ session('success') }}
          </div>
        @endif
          <div class="card mt-3">
            <div class="card-header">
              <h3 class="card-title">Daftar Laporan Posyandu</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Deskripsi</th>
                  <th>View</th>
                  <th>Download</th>
                  <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
                  @foreach ($data as $item)
                  <tr>
                    <th>{{ $loop->iteration}}</th>
                    <th>{{ $item->nama }}</th>
                    <th>{{ $item->deskripsi }}</th>
                    <th><a href="{{ url('/view', $item->id) }}">View</a></th>
                    <th><a href="{{ url('/download', $item->file) }}">Download</a></th>
                    <td>
                        <a href="/dashboard/dokumen/{{ $item->id }}/edit" class="btn btn-info">
                        <i class="fa fa-pencil-alt"></i>
                        </a>
                        <form action="/dashboard/dokumen/{{ $item->id }}" method="POST" class="d-inline">
                        @csrf
                        @method('delete')
                        <button class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?')">
                            <i class="fa fa-trash"></i>
                        </button>
                        </form>
                    </td>
                </tr>
                  @endforeach
                </tbody>
                <tfoot>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Deskripsi</th>
                  <th>View</th>
                  <th>Download</th>
                  <th>Aksi</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
@endsection

@push('add-style')
    <!-- DataTables -->
<link rel="stylesheet" href="{{ asset('backend/plugins') }}/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{ asset('backend/plugins') }}/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="{{ asset('backend/plugins') }}/datatables-buttons/css/buttons.bootstrap4.min.css">
@endpush

@push('add-script')
    <!-- DataTables  & Plugins -->
<script src="{{ asset('backend/plugins') }}/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('backend/plugins') }}/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('backend/plugins') }}/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('backend/plugins') }}/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{ asset('backend/plugins') }}/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('backend/plugins') }}/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('backend/plugins') }}/jszip/jszip.min.js"></script>
<script src="{{ asset('backend/plugins') }}/pdfmake/pdfmake.min.js"></script>
<script src="{{ asset('backend/plugins') }}/pdfmake/vfs_fonts.js"></script>
<script src="{{ asset('backend/plugins') }}/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('backend/plugins') }}/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('backend/plugins') }}/datatables-buttons/js/buttons.colVis.min.js"></script>

<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@endpush --}}

@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>File Posyandu</h1>
      </div>
      @include('includes.admin.alert')
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header d-inline">
              <h4>File Posyandu</h4>
              <a href="/dashboard/dokumen/create" class=" btn btn-primary mt-3">Tambah File Posyandu</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-striped" id="table-1">
                  <thead>
                    <tr>
                      <th class="text-center">
                        No
                      </th>
                      <th>Nama</th>
                      <th>Deskripsi</th>
                      <th>View</th>
                      <th>Download</th>
                      <th>Aksi</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($data as $item)
                  <tr>
                    <th>{{ $loop->iteration}}</th>
                    <th>{{ $item->nama }}</th>
                    <th>{{ $item->deskripsi }}</th>
                    <th><a href="{{ url('/dashboard/dokumen/view', $item->id) }}" class="btn btn-success">View</a></th>
                    <th><a href="{{ url('/dashboard/dokumen/download/'. $item->id) }}" class="btn btn-dark" onclick="return confirm('Apakah Anda Yakin Untuk Download File Ini?')">Download</a></th>
                    <td>
                        <a href="/dashboard/dokumen/{{ $item->id }}/edit" class="btn btn-info">
                        <i class="fa fa-pencil-alt"></i>
                        </a>
                        <a href="{{ route('dokumen.destroy', $item->id) }}" class="btn btn-danger" data-confirm-delete="true">
                          <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
                  @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="section-body">
      </div>
    </section>
  </div>
@endsection

resources/views/dokumen/view.blade.php
{{-- @extends('app-layouts.admin.index')

@section('content')
<iframe height="500px"  width="100%" src="/assets/{{$data->file}}"></iframe>
@endsection --}}

@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>View File</h1>
      </div>
      <div class="section-body">
        <iframe height="500px"  width="100%" src="{{ asset('storage/'. $data->file) }}"></iframe>
      </div>
    </section>
  </div>
@endsection