routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\BalitaController;
use App\Http\Controllers\BumilController;
use App\Http\Controllers\CheckupController;
use App\Http\Controllers\DokumentasiController;
use App\Http\Controllers\DokumentController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\HomeController;
// use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ImunisasiController;
use App\Http\Controllers\KaderController;
use App\Http\Controllers\ManajemenUserController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\ShowArticleController;
use App\Http\Controllers\SuperAdminAuthenticateController;
use App\Http\Controllers\SuperAdminHomepageController;
use App\Http\Controllers\VaksinasiController;
use App\Http\Controllers\VitaminController;
use App\Models\Article;
use App\Models\Balita;
use App\Models\Bumil;
use App\Models\Checkup;
use App\Models\Dokument;
use App\Models\Imunisasi;
use App\Models\Kader;
use App\Models\Vaksinasi;
use App\Models\Vitamin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('mainpage');
Route::get('/article/{article}', ShowArticleController::class)->name('show.article');

Route::get('/dashboard', function () {
    return view('dashboard', [
        'kader' => Kader::count(),
        'balita' => Balita::count(),
        'vitamin' => Vitamin::count(),
        'imunisasi' => Imunisasi::count(),
        'vaksinasi' => Vaksinasi::count(),
        'checkup' => Checkup::count(),
        'bumil' => Bumil::count(),
        'article' => Article::count(),
        'dokumen' => Dokument::count()
    ]);
})->middleware('auth')->name('dashboard');

Route::resource('/dashboard/kader', KaderController::class)->middleware('auth');
Route::resource('/dashboard/balita', BalitaController::class)->middleware('auth');
Route::resource('/dashboard/bumil', BumilController::class)->middleware('auth');
Route::resource('/dashboard/vitamin', VitaminController::class)->middleware('auth');
Route::resource('/dashboard/imunisasi', ImunisasiController::class)->middleware('auth');
Route::resource('/dashboard/vaksinasi', VaksinasiController::class)->middleware('auth');
Route::resource('/dashboard/article', ArticleController::class)->middleware('auth');
Route::resource('/dashboard/checkup', CheckupController::class)->middleware('auth');
Route::resource('/dashboard/dokumen', FileController::class)->middleware('auth');
Route::get('/dashboard/dokumen/download/{id}', [FileController::class, 'download'])->middleware('auth');
Route::get('/dashboard/dokumen/view/{id}',[FileController::class,'view'])->middleware('auth');

Route::middleware('guest')->group(function(){
    Route::controller(ResetPasswordController::class)->group(function (){
        Route::get('lupa-password', 'view')->name('lupa-password.view');
        Route::post('verify-email', 'verifyEmail')->name('verify.email');
        Route::get('reset-password', 'resetPasswordView')->name('reset-password.view');
        Route::post('lupa-password', 'reset')->name('lupa-password.store');
    }); 
});

Route::controller(SuperAdminAuthenticateController::class)->group(function(){
    Route::get('admin/login', 'loginView')->name('admin.login.view');
    Route::post('admin/login', 'login')->name('admin.login');
    Route::post('admin/logout', 'logout')->name('admin.logout');
});

Route::middleware('auth:superadmin')->group(function() {
    Route::get('admin/dashboard', [SuperAdminHomepageController::class, 'index'])->name('admin.index');

    Route::controller(ManajemenUserController::class)->group(function() {
        Route::get('admin/data-users', 'index')->name('user.index');
        Route::get('admin/tambah-user', 'addUser')->name('user.add');
        Route::post('admin/tambah-user', 'storeUser')->name('user.store');
        Route::delete('admin/hapus-user/{id}', 'deleteUser')->name('user.delete');
        Route::get('admin/data-user/{id}/ubah-password', 'ubahPasswordView')->name('user.changePwd');
        Route::post('admin/data-user/{id}/ubah-password', 'ubahPassword')->name('user.changePwdStore');
    });
});

require __DIR__.'/auth.php';

app/Models/Vitamin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vitamin extends Model
{
    use HasFactory;

    protected $table = 'vitamin';

    // protected $fillable = ['jenis_vitamin', 'keterangan', 'maksimal_umur_pengguna'];
    protected $guarded = [];

    public function checkup(){
        return $this->hasMany(Checkup::class);
    }
}

app/Http/Controllers/VitaminController.php
<?php

namespace App\Http\Controllers;

use App\Models\Vitamin;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class VitaminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Vitamin::all();
        $sweetalert_delete_title = 'Delete Data Vitamin!';
        $sweetalert_delete_msg = "Apakah yakin ingin hapus data vitamin?";
        confirmDelete($sweetalert_delete_title, $sweetalert_delete_msg);
        return view('vitamin.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vitamin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'jenis_vitamin' => 'required',
            'keterangan' => 'required',
            'maksimal_umur_tahun_pengguna' => 'required',
            'maksimal_umur_bulan_pengguna' => [
                'required',
                Rule::in(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'])
            ]
        ]);

        Vitamin::create($data);
        return redirect('/dashboard/vitamin')->with('success', 'Daftar Jenis Vitamin Berhasil di Tambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Vitamin::findOrFail($id);
        return view('vitamin.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'jenis_vitamin' => 'required',
            'keterangan' => 'required',
            'maksimal_umur_tahun_pengguna' => 'required',
            'maksimal_umur_bulan_pengguna' => [
                'required',
                Rule::in(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'])
            ]
        ]);

        $item = Vitamin::findOrFail($id);

        $item->update($data);
        return redirect('/dashboard/vitamin')->with('info', 'Daftar Jenis Vitamin Berhasil di Update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Vitamin::findOrFail($id);

        $item->delete();

        return redirect('/dashboard/vitamin')->with('danger', 'Daftar Jenis Vitamin Berhasil di Hapus');;
    }
}

resources/views/vitamin/create.blade.php
{{-- @extends('app-layouts.admin.index')

@section('content')
    <div class="content-wrapper">
        <section>
            <div class="row">
                <div class="col-lg-8">
                    <div class="card my-4">
                        <div class="card-header">
                            <div class="card-title">
                                <h5>Tambah Vitamin</h5>
                            </div>
                        </div>
                        <div class="card-shadow">
                            <div class="card-body">
                                <form action="/dashboard/vitamin" method="POST">
                                    @csrf
                                    <div class="form-group">
                                        <label for="jenis_vitamin">Jenis vitamin</label>
                                        <input type="text" class="form-control @error('jenis_vitamin') is-invalid @enderror"" name="jenis_vitamin" placeholder="Jenis vitamin" value="{{ old('jenis_vitamin') }}">
                                        @error('jenis_vitamin')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="keterangan">Keterangan</label>
                                        <input type="text" class="form-control @error('keterangan') is-invalid @enderror" name="keterangan" placeholder="Keterangan" value="{{ old('keterangan') }}">
                                        @error('keterangan')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="maksimal_umur_pengguna">Maksimal Umur</label>
                                        <input type="text" class="form-control @error('maksimal_umur_pengguna') is-invalid @enderror" name="maksimal_umur_pengguna" placeholder="maksimal_umur_pengguna" value="{{ old('maksimal_umur_pengguna') }}">
                                        @error('maksimal_umur_pengguna')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <button class="btn btn-primary btn-block" type="submit">Simpan</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection --}}

@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Tambah Data</h1>
      </div>
      <div class="section-body">
        <h2 class="section-title">Form Input Data Vitamin</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
              <form action="/dashboard/vitamin" method="POST">
                @csrf
                <div class="card-header">
                  <h4>Masukkan Data Vitamin Dengan Sesuai</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="jenis_vitamin">Jenis vitamin</label>
                        <input type="text" class="form-control @error('jenis_vitamin') is-invalid @enderror"" name="jenis_vitamin" placeholder="Jenis vitamin" value="{{ old('jenis_vitamin') }}">
                        @error('jenis_vitamin')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="keterangan">Keterangan</label>
                        <input type="text" class="form-control @error('keterangan') is-invalid @enderror" name="keterangan" placeholder="Keterangan" value="{{ old('keterangan') }}">
                        @error('keterangan')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="maksimal_umur_tahun_pengguna">Maksimal Umur (Tahun)</label>
                        <input type="text" class="form-control @error('maksimal_umur_tahun_pengguna') is-invalid @enderror" name="maksimal_umur_tahun_pengguna" placeholder="maksimal_umur_pengguna" value="{{ old('maksimal_umur_tahun_pengguna') }}" id="maksimal_umur_tahun_pengguna">
                        @error('maksimal_umur_tahun_pengguna')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="maksimal_umur_bulan_pengguna">Maksimal Umur (Bulan)</label>
                        <input type="text" class="form-control @error('maksimal_umur_bulan_pengguna') is-invalid @enderror" name="maksimal_umur_bulan_pengguna" placeholder="maksimal_umur_pengguna" value="{{ old('maksimal_umur_bulan_pengguna') }}" id="maksimal_umur_bulan_pengguna">
                        @error('maksimal_umur_bulan_pengguna')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                <div class="card-footer text-right">
                  <button class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/vitamin/edit.blade.php
{{-- @extends('app-layouts.admin.index')

@section('content')
    <div class="content-wrapper">
        <section>
            <div class="row">
                <div class="col-lg-8">
                    <div class="card my-4">
                        <div class="card-header">
                            <div class="card-title">
                                <h5>Ubah Vitamin</h5>
                            </div>
                        </div>
                        <div class="card-shadow">
                            <div class="card-body">
                                <form action="/dashboard/vitamin/{{ $data->id }}" method="POST">
                                    @method('PUT')
                                    @csrf
                                    <div class="form-group">
                                        <label for="jenis_vitamin">Jenis Vitamin</label>
                                        <input type="text" class="form-control @error('jenis_vitamin') is-invalid @enderror"" name="jenis_vitamin" placeholder="jenis_vitamin" value="{{ $data->jenis_vitamin }}">
                                        @error('jenis_vitamin')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="keterangan">Keterangan</label>
                                        <input type="text" class="form-control @error('keterangan') is-invalid @enderror"" name="keterangan" placeholder="keterangan" value="{{ $data->keterangan }}">
                                        @error('keterangan')
                                            <div class="invalid-feedback">
                                            {{ $message }}
                                            </div>
                                        @enderror
                                    </div>
                                    <button class="btn btn-primary btn-block" type="submit">Simpan</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection --}}

@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Update Data</h1>
      </div>
      <div class="section-body">
        <h2 class="section-title">Form Update Data Vitamin</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
              <form action="/dashboard/vitamin/{{ $data->id }}" method="POST">
                @method('PUT')
                @csrf
                <div class="card-header">
                  <h4>Masukkan Data Vitamin Dengan Sesuai</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="jenis_vitamin">Jenis Vitamin</label>
                        <input type="text" class="form-control @error('jenis_vitamin') is-invalid @enderror"" name="jenis_vitamin" placeholder="jenis_vitamin" value="{{ $data->jenis_vitamin }}">
                        @error('jenis_vitamin')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="keterangan">Keterangan</label>
                        <input type="text" class="form-control @error('keterangan') is-invalid @enderror"" name="keterangan" placeholder="keterangan" value="{{ $data->keterangan }}">
                        @error('keterangan')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="maksimal_umur_tahun_pengguna">Maksimal Umur (Tahun)</label>
                        <input type="text" class="form-control @error('maksimal_umur_tahun_pengguna') is-invalid @enderror"" name="maksimal_umur_tahun_pengguna" placeholder="maksimal_umur_pengguna tahun" value="{{ $data->maksimal_umur_tahun_pengguna }}">
                        @error('maksimal_umur_tahun_pengguna')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="maksimal_umur_bulan_pengguna">Maksimal Umur (Bulan)</label>
                        <input type="text" class="form-control @error('maksimal_umur_bulan_pengguna') is-invalid @enderror"" name="maksimal_umur_bulan_pengguna" placeholder="maksimal_umur_pengguna bulan" value="{{ $data->maksimal_umur_bulan_pengguna }}">
                        @error('maksimal_umur_bulan_pengguna')
                            <div class="invalid-feedback">
                            {{ $message }}
                            </div>
                        @enderror
                    </div>
                </div>
                <div class="card-footer text-right">
                  <button class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/vitamin/index.blade.php
@extends('app-layouts.admin.index')

@section('content')
<div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Data List Vitamin</h1>
      </div>
      @include('includes.admin.alert')
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header d-inline">
              <h4>Data Vitamin</h4>
              <a href="/dashboard/vitamin/create" class=" btn btn-primary mt-3">Tambah Data Vitamin</a>
              <a href="#" class=" btn btn-primary mt-3">Unduh Data</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-striped" id="table-1">
                  <thead>
                    <tr>
                      <th class="text-center">
                        No
                      </th>
                      <th>Jenis Vitamin</th>
                      <th>Keterangan</th>
                      <th>Maksimal Umur</th>
                      <th>Aksi</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($data as $item)
                    <tr>
                      <th class="text-center">{{ $loop->iteration}}</th>
                      <th>{{ $item->jenis_vitamin }}</th>
                      <th>{{ $item->keterangan }}</th>
                      <th>
                        {{ $item->maksimal_umur_tahun_pengguna }} tahun {{ $item->maksimal_umur_bulan_pengguna }} bulan
                      </th>
                      <td>
                          <a href="/dashboard/vitamin/{{ $item->id }}/edit" class="btn btn-info">
                          <i class="fa fa-pencil-alt"></i>
                          </a>
                          <a href="{{ route('vitamin.destroy', $item->id) }}" class="btn btn-danger" data-confirm-delete="true">
                            <i class="fa fa-trash"></i>
                          </a>
                      </td>
                  </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="section-body">
      </div>
    </section>
  </div>
@endsection